person:
  id: 110
  user-name: "人民警察"
  realName: '沈燕明 '
  date: 2018/12/12 23:59:59
  isDel: false
  maps: {k1: v1,k2: v2}
  lists:
    - cat
    - dog
    - pig
  address:
    addressId: 001
    country: '中国'
    isDel: true
---
server:
  port: 8080
spring:
  profiles: dev