## springCloud服务消费方的配置
server:
  port: 8200 #当前应用运行起来的端口
spring:
  application:
    name: service-consumer #当前应用的名称
eureka:
  instance:
    prefer-ip-address: true #使用IP地址作为注册服务的标识
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #eureka注册中心的地址