## 指定生效的profile
spring:
  profiles:
    active: dev

## 自定义的属性映射配置, 可以通过@ConfigurationProperties注解指定
person:
  id: 110
  user-name: "人民警察"
  realName: '沈燕明 '
  date: 2018/12/12 23:59:59
  isDel: false
  maps: {k1: v1,k2: v2}
  lists:
    - cat
    - dog
    - pig
  address:
    addressId: 001
    country: '中国'
    isDel: true

---
## 除了单独使用一个yml配置文件外, 同一个yml配置使用"---"也可以作为不同的profile
spring:
  profiles: line
server:
  port: 16166
