## springData JPA整合
spring:
  ## 这个配置放在这里就不生效...
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: ture
        show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE