spring:
  elasticsearch: ## spring data 对elasticsearch的配置
    rest:
      uris: http://127.0.0.1:9200
      connection-timeout: 10
      username:
      password:
    jest: ## jest 对elasticsearch的配置
      connection-timeout: 10
      uris: http://127.0.0.1:9200
      username:
      password:

##  springBoot对日志的配置
logging:
  level: debug #定义日志输出级别
  #file: springBoot.log #指定日志保存文件

## 自定义参数, 用来指定bbossmapper地址
elasticsearch:
  config:
    location: mapper/