## springCloud服务提供方的配置
server:
  port: 8002 #springBoot项目跑起来运行的端口
spring:
  application:
    name: service-provider #应用名称
eureka:
  instance:
    prefer-ip-address: true #使用服务的IP地址作为注册服务的标识
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #eureka服务器的地址
